CREATE TABLE Badges (
    BadgeID INT PRIMARY KEY IDENTITY,
    GUID UNIQUEIDENTIFIER NOT NULL,
    BadgeHash VARCHAR(255) NOT NULL,
    BadgeData NVARCHAR(MAX) NOT NULL,
    CreationDate DATETIME NOT NULL,
    ExpiryDate DATETIME,
    OwnerName NVARCHAR(255) NOT NULL,
    IssuerName NVARCHAR(255) NOT NULL,
    PgpSignature NVARCHAR(MAX)
);
