name: Deploy to Azure Function

on:
  push:
    branches:
      - dev  # Ou a branch que você usa para implantação

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Especifique a versão do Python que você usa

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ secrets.AZURE_FUNCTION_NAME }}  # Configurar nas Secrets do GitHub
        package: .  # Caminho para o diretório ou arquivo zip da sua aplicação
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}  # Configurar nas Secrets do GitHub

    - name: 'Finish Deployment'
      run: echo "Deployed to ${{ steps.fa.outputs.app-url }}"
